# Users API Plans - GKO ApiPlan CRDs
# Defines subscription plans with different access levels and quotas
---
apiVersion: gravitee.io/v1alpha1
kind: ApiPlan
metadata:
  name: users-api-free-plan
  namespace: gravitee-apis
  labels:
    app.kubernetes.io/name: users-api-free-plan
    app.kubernetes.io/component: api-plan
    api.gravitee.io/api: users-api
    api.gravitee.io/tier: free
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  # Reference to the API
  apiRef:
    name: users-api
    namespace: gravitee-apis
  
  # Reference to ManagementContext
  contextRef:
    name: gravitee-apim-context
    namespace: gravitee-apis
  
  # Plan details
  name: "Free Plan"
  description: "Free tier with limited access - 100 requests per day"
  
  # Plan order (display order in portal)
  order: 1
  
  # Security type
  security: API_KEY
  
  # Plan status
  status: PUBLISHED
  
  # Validation type for subscriptions
  validation: AUTO
  
  # Rate limiting for this plan
  flows:
    - name: "Free Tier Rate Limit"
      pathOperator:
        path: /
        operator: STARTS_WITH
      enabled: true
      pre:
        - name: "Daily Quota"
          policy: quota
          enabled: true
          configuration:
            quota:
              limit: 100
              periodTime: 1
              periodTimeUnit: DAYS
            key: "{#subscription.id}"
        - name: "Rate Limit"
          policy: rate-limit
          enabled: true
          configuration:
            rate:
              limit: 10
              periodTime: 1
              periodTimeUnit: MINUTES
  
  # Excluded groups (optional)
  excludedGroups: []
  
  # Characteristics for portal display
  characteristics:
    - "100 requests/day"
    - "10 requests/minute"
    - "Community support"
    - "Basic analytics"
---
apiVersion: gravitee.io/v1alpha1
kind: ApiPlan
metadata:
  name: users-api-standard-plan
  namespace: gravitee-apis
  labels:
    app.kubernetes.io/name: users-api-standard-plan
    app.kubernetes.io/component: api-plan
    api.gravitee.io/api: users-api
    api.gravitee.io/tier: standard
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  apiRef:
    name: users-api
    namespace: gravitee-apis
  
  contextRef:
    name: gravitee-apim-context
    namespace: gravitee-apis
  
  name: "Standard Plan"
  description: "Standard tier for production workloads - 10,000 requests per day"
  
  order: 2
  security: API_KEY
  status: PUBLISHED
  validation: MANUAL  # Requires approval
  
  flows:
    - name: "Standard Tier Limits"
      pathOperator:
        path: /
        operator: STARTS_WITH
      enabled: true
      pre:
        - name: "Daily Quota"
          policy: quota
          enabled: true
          configuration:
            quota:
              limit: 10000
              periodTime: 1
              periodTimeUnit: DAYS
            key: "{#subscription.id}"
        - name: "Rate Limit"
          policy: rate-limit
          enabled: true
          configuration:
            rate:
              limit: 100
              periodTime: 1
              periodTimeUnit: MINUTES
  
  characteristics:
    - "10,000 requests/day"
    - "100 requests/minute"
    - "Email support"
    - "Full analytics"
    - "SLA: 99.5%"
---
apiVersion: gravitee.io/v1alpha1
kind: ApiPlan
metadata:
  name: users-api-enterprise-plan
  namespace: gravitee-apis
  labels:
    app.kubernetes.io/name: users-api-enterprise-plan
    app.kubernetes.io/component: api-plan
    api.gravitee.io/api: users-api
    api.gravitee.io/tier: enterprise
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  apiRef:
    name: users-api
    namespace: gravitee-apis
  
  contextRef:
    name: gravitee-apim-context
    namespace: gravitee-apis
  
  name: "Enterprise Plan"
  description: "Enterprise tier with unlimited access and premium support"
  
  order: 3
  security: JWT  # JWT-based authentication for enterprise
  status: PUBLISHED
  validation: MANUAL
  
  # JWT security configuration
  securityDefinition: |
    {
      "signature": "RSA_RS256",
      "publicKeyResolver": "JWKS_URL",
      "jwksUrl": "https://auth.example.com/.well-known/jwks.json",
      "userClaim": "sub",
      "clientIdClaim": "azp"
    }
  
  flows:
    - name: "Enterprise Tier Limits"
      pathOperator:
        path: /
        operator: STARTS_WITH
      enabled: true
      pre:
        - name: "Rate Limit"
          policy: rate-limit
          enabled: true
          configuration:
            rate:
              limit: 1000
              periodTime: 1
              periodTimeUnit: MINUTES
  
  characteristics:
    - "Unlimited requests"
    - "1,000 requests/minute"
    - "24/7 Premium support"
    - "Advanced analytics"
    - "SLA: 99.99%"
    - "Dedicated support engineer"

