# Orders API Plans
---
apiVersion: gravitee.io/v1alpha1
kind: ApiPlan
metadata:
  name: orders-api-standard-plan
  namespace: gravitee-apis
  labels:
    app.kubernetes.io/name: orders-api-standard-plan
    app.kubernetes.io/component: api-plan
    api.gravitee.io/api: orders-api
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  apiRef:
    name: orders-api
    namespace: gravitee-apis

  contextRef:
    name: gravitee-apim-context
    namespace: gravitee-apis

  name: "Standard Plan"
  description: "Standard access to Orders API"

  order: 1
  security: API_KEY
  status: PUBLISHED
  validation: AUTO

  flows:
    - name: "Standard Limits"
      pathOperator:
        path: /
        operator: STARTS_WITH
      enabled: true
      pre:
        - name: "Rate Limit"
          policy: rate-limit
          enabled: true
          configuration:
            rate:
              limit: 100
              periodTime: 1
              periodTimeUnit: MINUTES

  characteristics:
    - "100 requests/minute"
    - "Standard support"

