# Products API Definition
# Owner: Catalog Team (catalog-team@example.com)
# Slack: #catalog-team-api
---
apiVersion: gravitee.io/v1alpha1
kind: ApiDefinition
metadata:
  name: products-api
  namespace: gravitee-apis
  labels:
    app.kubernetes.io/name: products-api
    app.kubernetes.io/component: api
    api.gravitee.io/category: e-commerce
    api.gravitee.io/version: v1
    team: catalog-team
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    api.gravitee.io/description: "Product Catalog API"
    api.gravitee.io/owner: "catalog-team"
    api.gravitee.io/contact: "catalog-team@example.com"
    api.gravitee.io/slack: "#catalog-team-api"
    api.gravitee.io/oncall: "catalog-team-oncall"
spec:
  contextRef:
    name: gravitee-apim-context
    namespace: gravitee-apis
  
  name: "Products API"
  version: "1.0.0"
  description: "RESTful API for product catalog management - Owned by Catalog Team"
  
  visibility: PUBLIC
  lifecycleState: PUBLISHED
  state: STARTED
  
  categories:
    - "E-Commerce"
    - "Catalog"
  
  tags:
    - "products"
    - "catalog"
    - "inventory"
    - "catalog-team"
  
  proxy:
    virtualHosts:
      - path: /api/v1/products
        overrideEntrypoint: true
    
    groups:
      - name: default-group
        endpoints:
          - name: products-service
            # Base URL - overridden per environment
            target: http://products-service.catalog-team.svc.cluster.local:8080
            weight: 1
            type: http
        
        loadBalancer:
          type: ROUND_ROBIN
        
        http:
          connectTimeout: 3000
          readTimeout: 5000
          useCompression: true
  
  flowMode: DEFAULT
  
  flows:
    - name: "All Requests"
      pathOperator:
        path: /
        operator: STARTS_WITH
      enabled: true
      
      pre:
        - name: "Rate Limiting"
          policy: rate-limit
          enabled: true
          configuration:
            rate:
              limit: 200
              periodTime: 1
              periodTimeUnit: MINUTES
        
        - name: "Cache"
          policy: cache
          enabled: true
          configuration:
            cacheName: products-cache
            timeToLiveSeconds: 300
            methods:
              - GET
      
      post:
        - name: "CORS"
          policy: cors
          enabled: true
          configuration:
            accessControlAllowOrigin:
              - "*"
            accessControlAllowMethods:
              - GET
              - OPTIONS
            accessControlAllowHeaders:
              - Content-Type
              - Authorization
            accessControlMaxAge: 86400
  
  analytics:
    enabled: true
    logging:
      mode: NONE
  
  metadata:
    - name: team
      value: catalog-team
      format: STRING
    - name: slack-channel
      value: "#catalog-team-api"
      format: STRING
    - name: oncall
      value: "catalog-team-oncall"
      format: STRING

