# External Secrets for Production
# Uses External Secrets Operator to sync secrets from Vault/AWS/GCP
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gravitee-admin-credentials-external
  namespace: gravitee-apis-prod
  labels:
    app.kubernetes.io/name: gravitee-credentials
    app.kubernetes.io/component: secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: gravitee-admin-credentials-external
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        GRAVITEE_USERNAME: "{{ .username }}"
        GRAVITEE_PASSWORD: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: gravitee/production/admin
        property: username
    - secretKey: password
      remoteRef:
        key: gravitee/production/admin
        property: password
---
# ClusterSecretStore for Vault (example)
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.example.com"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "gravitee-apis-prod"
          serviceAccountRef:
            name: "gravitee-external-secrets-sa"
            namespace: "gravitee-apis-prod"

