---
# Secret for Management API credentials
# NOTE: In production, use External Secrets Operator or Sealed Secrets
apiVersion: v1
kind: Secret
metadata:
  name: gravitee-admin-credentials
  namespace: gravitee-apis
  labels:
    app.kubernetes.io/name: gravitee-credentials
    app.kubernetes.io/component: secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  GRAVITEE_USERNAME: admin
  GRAVITEE_PASSWORD: "changeme"

