# ArgoCD Notifications Configuration for Gravitee APIs
# Sends notifications on sync events to Slack/Teams
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  # Slack service configuration
  service.slack: |
    token: $slack-token
    signingSecret: $slack-signing-secret
  
  # Notification templates
  template.app-sync-succeeded: |
    message: |
      ✅ *{{.app.metadata.name}}* sync succeeded!
      
      *Application:* {{.app.metadata.name}}
      *Environment:* {{index .app.metadata.labels "environment"}}
      *Revision:* {{.app.status.sync.revision | substr 0 7}}
      *Sync Status:* {{.app.status.sync.status}}
      *Health:* {{.app.status.health.status}}
      
      <{{.context.argocdUrl}}/applications/{{.app.metadata.name}}|View in ArgoCD>
    slack:
      attachments: |
        [{
          "color": "#18be52",
          "fields": [
            {"title": "Application", "value": "{{.app.metadata.name}}", "short": true},
            {"title": "Environment", "value": "{{index .app.metadata.labels \"environment\"}}", "short": true},
            {"title": "Revision", "value": "{{.app.status.sync.revision | substr 0 7}}", "short": true},
            {"title": "Author", "value": "{{(call .repo.GetCommitMetadata .app.status.sync.revision).Author}}", "short": true}
          ]
        }]
  
  template.app-sync-failed: |
    message: |
      ❌ *{{.app.metadata.name}}* sync failed!
      
      *Application:* {{.app.metadata.name}}
      *Environment:* {{index .app.metadata.labels "environment"}}
      *Error:* {{.app.status.operationState.message}}
      
      <{{.context.argocdUrl}}/applications/{{.app.metadata.name}}|View in ArgoCD>
    slack:
      attachments: |
        [{
          "color": "#E96D76",
          "fields": [
            {"title": "Application", "value": "{{.app.metadata.name}}", "short": true},
            {"title": "Environment", "value": "{{index .app.metadata.labels \"environment\"}}", "short": true},
            {"title": "Error", "value": "{{.app.status.operationState.message}}", "short": false}
          ]
        }]
  
  template.app-health-degraded: |
    message: |
      ⚠️ *{{.app.metadata.name}}* health degraded!
      
      *Application:* {{.app.metadata.name}}
      *Environment:* {{index .app.metadata.labels "environment"}}
      *Health Status:* {{.app.status.health.status}}
      
      <{{.context.argocdUrl}}/applications/{{.app.metadata.name}}|View in ArgoCD>
    slack:
      attachments: |
        [{
          "color": "#f4c030",
          "fields": [
            {"title": "Application", "value": "{{.app.metadata.name}}", "short": true},
            {"title": "Environment", "value": "{{index .app.metadata.labels \"environment\"}}", "short": true},
            {"title": "Health", "value": "{{.app.status.health.status}}", "short": true}
          ]
        }]
  
  template.app-deployed: |
    message: |
      🚀 *{{.app.metadata.name}}* deployed to production!
      
      *Application:* {{.app.metadata.name}}
      *Revision:* {{.app.status.sync.revision | substr 0 7}}
      *Deployed By:* {{.app.status.operationState.operation.initiatedBy.username}}
      
      <{{.context.argocdUrl}}/applications/{{.app.metadata.name}}|View in ArgoCD>
  
  # Triggers
  trigger.on-sync-succeeded: |
    - when: app.status.operationState.phase in ['Succeeded']
      send: [app-sync-succeeded]
  
  trigger.on-sync-failed: |
    - when: app.status.operationState.phase in ['Error', 'Failed']
      send: [app-sync-failed]
  
  trigger.on-health-degraded: |
    - when: app.status.health.status == 'Degraded'
      send: [app-health-degraded]
  
  trigger.on-deployed: |
    - when: app.status.operationState.phase in ['Succeeded'] and app.metadata.labels.environment == 'prod'
      send: [app-deployed]
  
  # Default triggers for all applications
  defaultTriggers: |
    - on-sync-succeeded
    - on-sync-failed
    - on-health-degraded
  
  # Subscriptions (can also be set via annotations)
  subscriptions: |
    - recipients:
        - slack:gravitee-deployments
      triggers:
        - on-sync-succeeded
        - on-deployed
    - recipients:
        - slack:gravitee-alerts
      triggers:
        - on-sync-failed
        - on-health-degraded
---
# Secret for notification tokens
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  slack-token: "REPLACE_WITH_SLACK_TOKEN"
  slack-signing-secret: "REPLACE_WITH_SIGNING_SECRET"

