# ManagementContext - Connection to Gravitee APIM
# This tells GKO how to communicate with Gravitee Management API
---
apiVersion: v1
kind: Secret
metadata:
  name: gravitee-admin-credentials
  namespace: gravitee-gko
type: Opaque
stringData:
  username: admin
  password: admin
---
apiVersion: gravitee.io/v1alpha1
kind: ManagementContext
metadata:
  name: gravitee-apim
  namespace: gravitee-gko
spec:
  # NOTE: baseUrl should NOT include /management - GKO adds it automatically
  baseUrl: http://gravitee-apim-api.gravitee.svc.cluster.local:83
  environmentId: DEFAULT
  organizationId: DEFAULT
  auth:
    secretRef:
      name: gravitee-admin-credentials
      namespace: gravitee-gko
